'use strict';
const D=window.DATA,$=id=>document.getElementById(id),fmt=n=>Math.round(n).toLocaleString('en-US'),monthName=m=>new Date(m+'-15T12:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'}),shortMonth=m=>new Date(m+'-15T12:00:00Z').toLocaleDateString('en-US',{month:'short',year:'2-digit',timeZone:'UTC'});
let geography='town';
const G=window.DISTRICTS;
const place=t=>t==='all'?'Connecticut statewide':geography==='town'?t:G[geography].label+' District '+t;
let program='SNAP',town='all',month=D.months.at(-1),measure='percent';const baseline='2025-07';
const townCount=(t,m)=>D.data[program][t][m]?.n??null;
const count=(t,m)=>t==='all'?D.towns.reduce((s,t)=>s+townCount(t,m),0):geography==='town'?townCount(t,m):G[geography].allocations[t].reduce((s,r)=>s+townCount(r.town,m)*r.weight,0);
const loss=t=>count(t,baseline)-count(t,month),percent=t=>count(t,baseline)>0?100*loss(t)/count(t,baseline):null;
function opts(id,items){items.forEach(([v,n])=>{const o=document.createElement('option');o.value=v;o.textContent=n;$(id).append(o);});}
opts('town',D.towns.map(t=>[t,t]));opts('month',D.months.filter(m=>m>=baseline).map(m=>[m,monthName(m)]));$('month').value=month;
$('updated').textContent=new Date(D.updated).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'America/New_York'});$('latest').textContent='Latest reporting month: '+monthName(D.months.at(-1));
$('geography').onchange=e=>{geography=e.target.value;town='all';$('town').innerHTML='<option value="all">Statewide · 169 municipalities</option>';opts('town',geography==='town'?D.towns.map(t=>[t,t]):Object.keys(G[geography].allocations).sort((a,b)=>a-b).map(id=>[id,place(id)]));render();};
$('town').onchange=e=>{town=e.target.value;render();};$('month').onchange=e=>{month=e.target.value;render();};$('measure').onchange=e=>{measure=e.target.value;renderMap();};$('reset').onclick=()=>choose('all');
for(const p of ['SNAP','Medicaid'])$(p.toLowerCase()).onclick=()=>{program=p;render();};
function choose(t){town=t;$('town').value=t;render();}
function metric(id,labelId,value,lossLabel,gainLabel,suffix=''){const gain=value<0;$(id).textContent=value===null?'Not available':(suffix?Math.abs(value).toFixed(1):fmt(Math.abs(value)))+suffix;$(id).className=gain?'gain':'';$(labelId).textContent=gain?gainLabel:lossLabel;}
function color(v){if(v===null)return '#dbe2e7';if(v<0)return '#3b9292';if(v===0)return '#e5edef';const limits=measure==='percent'?[5,10,20]:[100,500,2000];return v<limits[0]?'#adcbe9':v<limits[1]?'#719ed0':v<limits[2]?'#386fae':'#204a80';}
function render(){for(const p of ['SNAP','Medicaid'])$(p.toLowerCase()).setAttribute('aria-pressed',String(program===p));$('scope').textContent=place(town)+' · '+program;const estimated=geography!=='town'&&town!=='all';$('unit').textContent=estimated?'Estimated counts · population allocation':'Published assistance-category counts';$('chart-key').textContent=estimated?'Estimated count':'Published count';$('selection-label').textContent=geography==='town'?'Municipality':G[geography].label+' district';$('geography-note').textContent=geography==='town'?'Select a municipality to focus the figures and trend.':G[geography].vintage+' · 2020 Census population weights. Select a district to view estimated losses and its trend.';$('allocation-details').hidden=!estimated;if(estimated)$('allocations').innerHTML=G[geography].allocations[town].map(r=>'<tr><td>'+r.town+'</td><td>'+(r.weight*100).toFixed(2)+'%</td><td>'+fmt((townCount(r.town,baseline)-townCount(r.town,month))*r.weight)+'</td></tr>').join('');metric('loss','loss-label',loss(town),'Net enrollment loss','Net enrollment gain');metric('percent','percent-label',percent(town),'Percent loss','Percent gain','%');const prev=D.months[D.months.indexOf(month)-1];metric('momentum','momentum-label',count(town,prev)-count(town,month),'Loss since previous month','Gain since previous month');$('momentum-note').textContent=monthName(prev)+' to '+monthName(month);$('baseline-count').textContent=fmt(count(town,baseline));$('current-count').textContent=fmt(count(town,month));$('selected-month').textContent=monthName(month);$('chart-subtitle').textContent='January 2025 through '+monthName(month)+' · OBBBA enacted July 4, 2025';renderMap();renderChart();}
const allCoords=D.geo.features.flatMap(f=>(f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates).flat(2));const xs=allCoords.map(p=>p[0]),ys=allCoords.map(p=>p[1]);const xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);const width=600,height=360,sx=(width-20)/(xmax-xmin),sy=(height-20)/(ymax-ymin),scale=Math.min(sx,sy/1.32),project=p=>[10+(p[0]-xmin)*scale,10+(ymax-p[1])*scale*1.32];
function geometryPath(f){return (f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates).map(poly=>poly.map(ring=>ring.map((p,i)=>(i?'L':'M')+project(p).map(n=>n.toFixed(2)).join(',')).join(' ')+'Z').join(' ')).join(' ');}
function renderMap(){const district=geography!=='town';let html='<svg viewBox="0 0 600 360" role="group" aria-label="Connecticut '+(district?G[geography].label+' district':'municipal')+' enrollment changes">';
for(const f of (district?G[geography].geo:D.geo).features){const t=district?f.properties.id:f.properties.Town,v=measure==='percent'?percent(t):loss(t),label=place(t)+': '+(district?'estimated ':'')+(v===null?'percentage unavailable':(measure==='percent'?Math.abs(v).toFixed(1)+'%':fmt(Math.abs(v)))+(v<0?' gain':' loss'));html+='<path d="'+geometryPath(f)+'" fill="'+color(v)+'" data-town="'+t+'" tabindex="0" role="button" aria-label="'+label+'" class="'+(district?'district ':'')+(town===t?'selected':'')+'"><title>'+label+'</title></path>';}
html+='</svg>';$('map').innerHTML=html;$('map').querySelectorAll('[data-town]').forEach(p=>{p.onclick=()=>choose(p.dataset.town);p.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(p.dataset.town);}};p.onmouseenter=p.onfocus=()=>detail(p.dataset.town);p.onmouseleave=p.onblur=()=>detail(town);});const labels=measure==='percent'?['Gain','No change','0–<5%','5–<10%','10–<20%','20%+']:['Gain','No change','>0–<100','100–<500','500–<2,000','2,000+'],colors=['#3b9292','#e5edef','#adcbe9','#719ed0','#386fae','#204a80'];$('legend').innerHTML='<b class="legend-caption">'+(district?'Estimated district losses':'Town losses')+'</b>'+labels.map((l,i)=>'<span><i style="background:'+colors[i]+'"></i>'+l+'</span>').join('')+'<span><i style="background:#dbe2e7"></i>No valid baseline</span>';detail(town);}
function detail(t){if(t==='all'){$('map-detail').textContent='Statewide view. Select a '+(geography==='town'?'municipality':'district')+' to explore changes.';return;}const l=loss(t),p=percent(t);$('map-detail').textContent=place(t)+' · '+(geography==='town'?'':'estimated ')+fmt(Math.abs(l))+' net '+(l<0?'gain':'loss')+' ('+(p===null?'percentage unavailable':Math.abs(p).toFixed(1)+'%')+') · '+fmt(count(t,month))+' in '+monthName(month);}
function renderChart(){let ms=D.months.filter(m=>m<=month),values=ms.map(m=>count(town,m));let w=560,h=315,pad={l:57,r:18,t:24,b:42},max=Math.max(...values)*1.08||1;const x=i=>pad.l+i*(w-pad.l-pad.r)/(ms.length-1),y=n=>h-pad.b-n/max*(h-pad.t-pad.b);let s='<svg viewBox="0 0 560 315" role="img" aria-label="Monthly '+program+' assistance-category counts for '+place(town)+'"><title>Monthly counts; exact values are in the monthly data table below</title>';for(let i=0;i<=4;i++){let v=max*i/4;s+='<line x1="57" x2="542" y1="'+y(v)+'" y2="'+y(v)+'" stroke="#dce5f0"/><text x="49" y="'+(y(v)+4)+'" text-anchor="end">'+(v>=10000?Math.round(v/1000)+'k':fmt(v))+'</text>';}
let bi=ms.indexOf(baseline),bx=x(bi),labelX=Math.min(bx+12,365);s+='<rect x="'+bx+'" y="24" width="'+(542-bx)+'" height="249" fill="#965b6c" opacity="0.10"/><line x1="'+bx+'" x2="'+bx+'" y1="24" y2="273" stroke="#965b6c" stroke-width="1.5" stroke-dasharray="4 4"/><path d="M'+(bx-5)+',12 L'+bx+',7 L'+(bx+5)+',12 L'+bx+',17 Z" fill="#965b6c"/><text x="'+labelX+'" y="16" style="fill:#804657;font-weight:700;font-size:12px">OBBBA enacted · July 4, 2025</text>';let coords=values.map((v,i)=>x(i)+','+y(v));s+='<path d="M'+x(0)+',273 L'+coords.join(' L')+' L'+x(ms.length-1)+',273 Z" fill="#204a800e"/><polyline points="'+coords.join(' ')+'" fill="none" stroke="#204a80" stroke-width="3"/>';for(let i=0;i<ms.length;i++){s+='<circle cx="'+x(i)+'" cy="'+y(values[i])+'" r="3.5" fill="#204a80"><title>'+monthName(ms[i])+': '+fmt(values[i])+'</title></circle>';if(i===0||i===bi||i===ms.length-1||(i%4===0&&Math.abs(i-bi)>1&&ms.length-1-i>1))s+='<text x="'+x(i)+'" y="300" text-anchor="middle">'+shortMonth(ms[i])+'</text>';}s+='<circle cx="'+bx+'" cy="'+y(values[bi])+'" r="6" fill="#965b6c" stroke="#ffffff" stroke-width="2"><title>July 4, 2025: OBBBA enacted. Marker uses the July monthly count; timing does not establish causation.</title></circle></svg>';$('chart').innerHTML=s;$('monthly').innerHTML=ms.map(m=>'<tr><td>'+monthName(m)+'</td><td>'+fmt(count(town,m))+'</td><td>'+fmt(count(town,baseline)-count(town,m))+'</td></tr>').join('');}

render();
